version: '3.9'

services:
  backend_node_nest:
    container_name: backend_node_nest
    build:
      context: ./back_node_nest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - fullstack-network
    depends_on:
      - pg_postgres

  frontend_ts_angular:
    container_name: frontend_ts_angular
    build:
      context: ./front_ts_angular
      dockerfile: Dockerfile
    ports:
      - "889:80"
    networks:
      - fullstack-network
    depends_on:
      - backend_node_nest

  pg_postgres:
    container_name: pg_postgres
    image: postgres:13
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: bd_backend_nest_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin54321
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack-network

  server_nginx:
    container_name: server_nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "888:80"
    networks:
      - fullstack-network
    depends_on:
      - backend_node_nest
      - frontend_ts_angular

networks:
  fullstack-network:
    driver: bridge

volumes:
  postgres_data
    